CREATE TABLE ORI_AUTHORITY
(
  NAME_ VARCHAR(50) NOT NULL
);
CREATE INDEX FK_AUTHORITY
  ON ORI_AUTHORITY (NAME_);

CREATE TABLE ORI_USER
(
  ID_                 BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  LOGIN_              VARCHAR(50)            NOT NULL,
  PASSWORD_HASH_      VARCHAR(60),
  FIRST_NAME_         VARCHAR(50),
  LAST_NAME_          VARCHAR(50),
  EMAIL_              VARCHAR(100),
  ACTIVATED_          BIT(1)                 NOT NULL,
  LANG_KEY_           VARCHAR(5),
  ACTIVATION_KEY_     VARCHAR(20),
  RESET_KEY_          VARCHAR(20),
  CREATED_BY_         VARCHAR(50)            NOT NULL,
  CREATED_DATE_       TIMESTAMP              NOT NULL,
  RESET_DATE_         TIMESTAMP,
  LAST_MODIFIED_BY_   VARCHAR(50),
  LAST_MODIFIED_DATE_ TIMESTAMP
);
CREATE UNIQUE INDEX EMAIL
  ON ORI_USER (EMAIL_);
CREATE UNIQUE INDEX IDX_USER_EMAIL
  ON ORI_USER (EMAIL_);
CREATE UNIQUE INDEX IDX_USER_LOGIN
  ON ORI_USER (LOGIN_);
CREATE UNIQUE INDEX LOGIN
  ON ORI_USER (LOGIN_);


CREATE TABLE ORI_USER_AUTHORITY
(
  USER_ID_        BIGINT(20)  NOT NULL,
  AUTHORITY_NAME_ VARCHAR(50) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (USER_ID_, AUTHORITY_NAME_),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID_) REFERENCES ORI_USER (ID_),
  CONSTRAINT FK_AUTHORITY_NAME FOREIGN KEY (AUTHORITY_NAME_) REFERENCES ORI_AUTHORITY (NAME_)
);
CREATE INDEX FK_AUTHORITY_NAME
  ON ORI_USER_AUTHORITY (AUTHORITY_NAME_);

CREATE TABLE ORI_PERSISTENT_TOKEN
(
  SERIES_      VARCHAR(76) PRIMARY KEY NOT NULL,
  USER_ID_     BIGINT(20),
  TOKEN_VALUE_ VARCHAR(76)             NOT NULL,
  TOKEN_DATE_  DATE,
  IP_ADDRESS_  VARCHAR(39),
  USER_AGENT_  VARCHAR(255),
  CONSTRAINT FK_USER_PERSISTENT_TOKEN FOREIGN KEY (USER_ID_) REFERENCES ORI_USER (ID_)
);
CREATE INDEX FK_USER_PERSISTENT_TOKEN
  ON ORI_PERSISTENT_TOKEN (USER_ID_);